Repository alpenlabs/alpen, pull requests merged in 2025-09, with the labels that each got.

#1000 Part 1: Mock Bridge foundations
  Cargo.lock
  Cargo.toml
  bin/strata-client/src/rpc_server.rs
  crates/primitives/src/constants.rs
  crates/rpc/api/src/lib.rs
  crates/rpc/types/src/types.rs
  crates/util/python-utils/Cargo.toml
  crates/util/python-utils/src/bridge/mod.rs
  crates/util/python-utils/src/bridge/musig_signer.rs
  crates/util/python-utils/src/bridge/types.rs
  crates/util/python-utils/src/constants.rs
  crates/util/python-utils/src/drt.rs
  crates/util/python-utils/src/error.rs
  crates/util/python-utils/src/lib.rs
  crates/util/python-utils/src/parse.rs
  crates/util/python-utils/src/taproot.rs
  functional-tests/entry.py
  functional-tests/envs/env_control_builder.py
  functional-tests/envs/testenv.py
  functional-tests/factory/alpen_client.py
  functional-tests/factory/factory.py
  functional-tests/mixins/bridge_mixin.py
  functional-tests/tests/prover/prover_el_deposit_withdraw.py
  functional-tests/utils/utils.py
Labels: P1 - Blocks Release

#995 Convert chain worker crate to use service framework
  Cargo.lock
  crates/chain-worker/Cargo.toml
  crates/chain-worker/src/builder.rs
  crates/chain-worker/src/context.rs
  crates/chain-worker/src/errors.rs
  crates/chain-worker/src/handle.rs
  crates/chain-worker/src/lib.rs
  crates/chain-worker/src/message.rs
  crates/chain-worker/src/service.rs
  crates/chain-worker/src/worker.rs
  crates/chainexec/src/errors.rs
  crates/chainexec/src/exec_context.rs
  crates/chainexec/src/executor.rs
  crates/chainexec/src/lib.rs
  crates/consensus-logic/src/fork_choice_manager.rs
  crates/service/src/builder.rs
  crates/service/src/command.rs
  crates/service/src/lib.rs
  crates/service/src/status.rs
  crates/service/src/types.rs
Labels: P2 - Nice to Have

#1023 functional-tests: move from `poetry` to `uv`
  .github/dependabot.yml
  .github/workflows/functional.yml
  .github/workflows/main-eest.yml
  .gitignore
  .justfile
  crates/util/python-utils/pyproject.toml
  functional-tests/README.md
  functional-tests/envs/env_control_builder.py
  functional-tests/envs/rollup_params_cfg.py
  functional-tests/envs/testenv.py
  functional-tests/factory/alpen_client.py
  functional-tests/factory/config.py
  functional-tests/factory/factory.py
  functional-tests/factory/seqrpc.py
  functional-tests/poetry.lock
  functional-tests/poetry.toml
  functional-tests/pyproject.toml
  functional-tests/run_test.sh
  functional-tests/utils/transaction.py
  functional-tests/utils/utils.py
  functional-tests/uv.lock
Labels: python, P2 - Nice to Have

#1001 Part 2: Mock bridge tx
  crates/util/python-utils/src/bridge/dt.rs
  crates/util/python-utils/src/bridge/mod.rs
  crates/util/python-utils/src/bridge/withdrawal.rs
  crates/util/python-utils/src/error.rs
  crates/util/python-utils/src/parse.rs
Labels: P1 - Blocks Release

#1037 test: fix leftover from #1031
  functional-tests/tests/cl_reorg_resume_blockproduction.py
Labels: P0 - Blocks Development

#1044 ci: breakdown coverage from unit vs functional tests
  .github/workflows/test-coverage.yml
Labels: github_actions, P2 - Nice to Have

#1065 log: Bitcoin `Buf32` types reverse hex
  bin/strata-dbtool/src/output/broadcaster.rs
  crates/asm-types/src/ops.rs
  crates/btcio/Cargo.toml
  crates/btcio/src/broadcaster/handle.rs
  crates/db/src/types.rs
  crates/primitives/src/batch.rs
  crates/primitives/src/l1/block.rs
  crates/primitives/src/l1/btc.rs
  crates/primitives/src/l1/status.rs
  crates/state/src/bridge_state.rs
  crates/state/src/client_state.rs
Labels: P2 - Nice to Have
