Repository alpenlabs/alpen, pull requests merged in 2025-07, with the labels that each got.

#943 chore(func-tests): add `ty` as a type checker
  functional-tests/poetry.lock
  functional-tests/pyproject.toml
Labels: P2 - Nice to Have

#944 backport: fix(cli) recovery (#932)
  Cargo.lock
  Cargo.toml
  bin/alpen-cli/Cargo.toml
  bin/alpen-cli/src/cmd/debug.rs
  bin/alpen-cli/src/cmd/deposit.rs
  bin/alpen-cli/src/cmd/mod.rs
  bin/alpen-cli/src/cmd/recover.rs
  bin/alpen-cli/src/main.rs
  bin/alpen-cli/src/recovery.rs
Labels: P1 - Blocks Release

#952 ci: fix name for test-coverage
  .github/workflows/test-coverage.yml
Labels: P2 - Nice to Have

#950 feat(asm): implement core subprotocol with proof verification
  Cargo.lock
  bin/alpen-reth/Cargo.toml
  bin/datatool/Cargo.toml
  crates/asm/common/Cargo.toml
  crates/asm/common/src/error.rs
  crates/asm/common/src/genesis.rs
  crates/asm/common/src/lib.rs
  crates/asm/common/src/logging.rs
  crates/asm/common/src/msg.rs
  crates/asm/common/src/subprotocol.rs
  crates/asm/logs/src/constants.rs
  crates/asm/moho-program/src/input.rs
  crates/asm/moho-program/src/program.rs
  crates/asm/stf/Cargo.toml
  crates/asm/stf/src/preprocess.rs
  crates/asm/stf/src/stage.rs
  crates/asm/stf/src/stf.rs
  crates/asm/subprotocols/bridge-v1/Cargo.toml
  crates/asm/subprotocols/bridge-v1/src/constants.rs
  crates/asm/subprotocols/bridge-v1/src/lib.rs
  crates/asm/subprotocols/core/Cargo.toml
  crates/asm/subprotocols/core/src/constants.rs
  crates/asm/subprotocols/core/src/error.rs
  crates/asm/subprotocols/core/src/handlers/checkpoint.rs
  crates/asm/subprotocols/core/src/handlers/mod.rs
  crates/asm/subprotocols/core/src/lib.rs
  crates/asm/subprotocols/core/src/messages/l1_to_l2.rs
  crates/asm/subprotocols/core/src/messages/l2_to_l1.rs
  crates/asm/subprotocols/core/src/messages/mod.rs
  crates/asm/subprotocols/core/src/parsing/checkpoint.rs
  crates/asm/subprotocols/core/src/parsing/mod.rs
  crates/asm/subprotocols/core/src/types.rs
  crates/asm/subprotocols/core/src/verification/mod.rs
  crates/asm/subprotocols/core/src/verification/proof.rs
  crates/asm/subprotocols/core/src/verification/signature.rs
  crates/asm/subprotocols/core/src/verification/state_transition.rs
Labels: consensus, P2 - Nice to Have
